### ISSUE TITLE
💥 [DevOps] Kubernetes Deployment – Add Resources to Webapp and Backend Pods

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social-Deploy-Rebranding#102]
## 💥 DevOps Ticket

Kubernetes Deployment – Add Resources to Webapp and Backend Pods.

```yaml
          resources:
            limits:
              memory: 2G
            requests:
              memory: 1G
```
